# Generated by Django 2.2.4 on 2019-10-08 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='search',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('res_id', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('area', models.CharField(max_length=50)),
                ('cuisines', models.CharField(max_length=300)),
                ('avg_rating', models.FloatField(max_length=2)),
                ('avg_cost', models.IntegerField()),
            ],
        ),
    ]
