# Generated by Django 2.2.4 on 2019-10-12 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bonbon', '0002_auto_20191012_2320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='res',
            name='link',
        ),
    ]
