# Generated by Django 2.2.4 on 2019-10-12 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonbon', '0003_remove_res_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='res',
            name='link',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
