# Generated by Django 2.2.4 on 2019-10-14 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonbon', '0006_auto_20191013_0512'),
    ]

    operations = [
        migrations.AddField(
            model_name='res',
            name='cate',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='res',
            name='link',
            field=models.CharField(max_length=900, null=True),
        ),
    ]
