# Generated by Django 2.2.4 on 2019-10-27 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonbon', '0007_auto_20191014_1550'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='day',
        ),
        migrations.AddField(
            model_name='bill',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
